Bugfix and enhancement
mjsumpter/obsidian-tag-page pull request #23
Opened 2024-05-24 02:39 UTC by duckfarts

# Bugfixes
 - Fixes issue where you can't create tag pages for nested tags

# Enhancements
 - Links show full link name now instead of just `*`
 - Changes output from unordered lists of (tags + link) to a table of (link + tags) so the content can be sorted

2024-05-30 19:49 UTC, mjsumpter requested changes
Hey @duckfarts , see my comments below for more details. Main takeaways:

1. I would recommend changing this PR to _only_ be the bugfix. The bug fix is good as is, and works!
2. The tables are not working correctly, and more work needs to be done on them to address all use cases.

Thanks for your work on that, let me know what you'd like to do!

2024-05-30 19:49 UTC, mjsumpter commented on main.ts
> +		const filename = `${cleanedTag.replace('#', '').replaceAll("/","_")}${
This is a good fix, and works as expected!

2024-05-30 19:49 UTC, mjsumpter commented on src/utils/pageContent.ts
These changes may be working for your use cases, but I'm seeing mostly broken formatting on my end. A couple screenshots below.

I don't hate your idea of writing this into tables and expanding the link title (instead of the asterisk), but more work will need to be done to make that work correctly.

<img width="606" alt="Screenshot 2024-05-30 at 1 40 42 PM" src="https://github.com/mjsumpter/obsidian-tag-page/assets/40173937/6e753fde-8b68-4ac6-9b7c-8f6d77fb17c8">
<img width="566" alt="Screenshot 2024-05-30 at 1 41 32 PM" src="https://github.com/mjsumpter/obsidian-tag-page/assets/40173937/cfd622df-56ea-4c10-b04f-3e3993c5fc8c">


There are a few problems here:
1. The links still have `|*` which breaks the table formatting
2. It breaks a bit of the intended functionality - specifically that nested bullets are grouped with their parent (i.e. if I have an outline format with a tag, than sub-bullets in the outline are grouped together) 
3. It doesn't seem to work for nested tags (i.e. `#some-tag/*`). Each subheading should have a new table

2024-06-02 07:39 UTC, closed without merging

2024-06-02 11:09 UTC, duckfarts commented on src/utils/pageContent.ts
I separated the fix and link name enhancement out to separate PRs, working more on the tables enhancement.

For the tables enhancement:
1. Not seeing this issue, not sure if it's related to page names or maybe me being sloppy with how to make a pull request (I actually edited the main.js file in the plugin folder, then replicated my changes in the source files)

2. Yeah, I see what you mean for the nested bullets for excerpts from the same page. I'm trying to think if there's a way to do this or maybe other paths to try.

3. Also not seeing this issue, not sure what you mean for new tables for subheadings.

Thanks for your feedback (and patience)

Example output:
<img width="643" alt="TagPage_TagTableExample" src="https://github.com/mjsumpter/obsidian-tag-page/assets/24978179/f0635f8a-8267-4eea-a457-ce332501d805">